// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using CalderaReport.Domain.Data;

#nullable disable

namespace API.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814003327_AddingActivityMappingTable")]
    partial class AddingActivityMappingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Classes.DB.Activity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PGCRImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Classes.DB.ActivityHashMapping", b =>
                {
                    b.Property<long>("SourceHash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SourceHash"));

                    b.Property<long>("CanonicalActivityId")
                        .HasColumnType("bigint");

                    b.HasKey("SourceHash");

                    b.HasIndex("CanonicalActivityId");

                    b.ToTable("ActivityHashMapping");
                });

            modelBuilder.Entity("Classes.DB.ActivityReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ActivityReports");
                });

            modelBuilder.Entity("Classes.DB.ActivityType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OpTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpTypeId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("Classes.DB.OpType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OpTypes");
                });

            modelBuilder.Entity("Classes.DB.Player", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayNameCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastPlayedActivityInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdateStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUpdateStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MembershipType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Classes.DB.PlayerActivityRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("FastestCompletion")
                        .HasColumnType("interval");

                    b.Property<long>("FastestCompletionActivityReportId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TotalTimePlayed")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("FastestCompletionActivityReportId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerActivityRecords");
                });

            modelBuilder.Entity("Classes.DB.Activity", b =>
                {
                    b.HasOne("Classes.DB.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("Classes.DB.ActivityHashMapping", b =>
                {
                    b.HasOne("Classes.DB.Activity", "CanonicalActivity")
                        .WithMany()
                        .HasForeignKey("CanonicalActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalActivity");
                });

            modelBuilder.Entity("Classes.DB.ActivityReport", b =>
                {
                    b.HasOne("Classes.DB.Activity", "Activity")
                        .WithMany("ActivityReports")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classes.DB.Player", "Player")
                        .WithMany("ActivityReports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Classes.DB.ActivityType", b =>
                {
                    b.HasOne("Classes.DB.OpType", "OpType")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("OpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpType");
                });

            modelBuilder.Entity("Classes.DB.PlayerActivityRecord", b =>
                {
                    b.HasOne("Classes.DB.Activity", "Activity")
                        .WithMany("PlayerActivityRecords")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classes.DB.ActivityReport", "FastestCompletionActivityReport")
                        .WithMany()
                        .HasForeignKey("FastestCompletionActivityReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Classes.DB.Player", "Player")
                        .WithMany("PlayerActivityRecords")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("FastestCompletionActivityReport");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Classes.DB.Activity", b =>
                {
                    b.Navigation("ActivityReports");

                    b.Navigation("PlayerActivityRecords");
                });

            modelBuilder.Entity("Classes.DB.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Classes.DB.OpType", b =>
                {
                    b.Navigation("ActivityTypes");
                });

            modelBuilder.Entity("Classes.DB.Player", b =>
                {
                    b.Navigation("ActivityReports");

                    b.Navigation("PlayerActivityRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
