// <auto-generated />
using System;
using Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129200352_ReAddLastCrawled")]
    partial class ReAddLastCrawled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.DB.Activity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OpTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpTypeId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.DB.ActivityReport", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedsFullCheck")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("Id");

                    b.HasIndex("Id", "ActivityId");

                    b.HasIndex("Id", "ActivityId", "Date");

                    b.ToTable("ActivityReports");
                });

            modelBuilder.Entity("Domain.DB.ActivityReportPlayer", b =>
                {
                    b.Property<long>("ActivityReportId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("ActivityReportId", "PlayerId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ActivityReportId", "PlayerId")
                        .HasFilter("\"Completed\" = TRUE");

                    b.HasIndex("ActivityId", "Completed", "Duration")
                        .HasFilter("\"Completed\" = TRUE");

                    b.HasIndex("ActivityReportId", "PlayerId", "Duration");

                    b.HasIndex("ActivityReportId", "PlayerId", "Score");

                    b.ToTable("ActivityReportPlayers");
                });

            modelBuilder.Entity("Domain.DB.OpType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OpTypes");
                });

            modelBuilder.Entity("Domain.DB.Player", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayNameCode")
                        .HasColumnType("integer");

                    b.Property<string>("FullDisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCrawlCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCrawlStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPlayedCharacterBackgroundPath")
                        .HasColumnType("text");

                    b.Property<string>("LastPlayedCharacterEmblemPath")
                        .HasColumnType("text");

                    b.Property<int>("MembershipType")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsFullCheck")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Domain.DB.PlayerCrawlQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerCrawlQueue");
                });

            modelBuilder.Entity("Domain.DB.PlayerLeaderboard", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<int>("LeaderboardType")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FullDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ActivityId", "LeaderboardType");

                    b.HasIndex("ActivityId", "LeaderboardType", "Rank");

                    b.ToTable("PlayerLeaderboards");
                });

            modelBuilder.Entity("Domain.DB.Activity", b =>
                {
                    b.HasOne("Domain.DB.OpType", "OpType")
                        .WithMany("Activities")
                        .HasForeignKey("OpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpType");
                });

            modelBuilder.Entity("Domain.DB.ActivityReport", b =>
                {
                    b.HasOne("Domain.DB.Activity", "Activity")
                        .WithMany("ActivityReports")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Domain.DB.ActivityReportPlayer", b =>
                {
                    b.HasOne("Domain.DB.ActivityReport", "ActivityReport")
                        .WithMany("Players")
                        .HasForeignKey("ActivityReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DB.Player", "Player")
                        .WithMany("ActivityReportPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityReport");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.DB.PlayerLeaderboard", b =>
                {
                    b.HasOne("Domain.DB.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.DB.Activity", b =>
                {
                    b.Navigation("ActivityReports");
                });

            modelBuilder.Entity("Domain.DB.ActivityReport", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Domain.DB.OpType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Domain.DB.Player", b =>
                {
                    b.Navigation("ActivityReportPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
